version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

language: scala
env: ADOPTOPENJDK=8
scala:
  - 2.12
  - 2.12.next
  - 2.13
script: sbt test

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: release
      script: sbt ci-release

notifications:
  email:
    on_success: never
    recipients:
      secure: SPXQ3ZDQom41L8VKaFVx1XqqJyiHgDWTIseXegm+7SUdSZ+jPIVlqRvrSw0ubsIAYUPqyKOxZfnv40WbJ1g5c0kDNzQxlcHW7BPOMdAWkD64VQdk9d3uClloINeIPu4coD+IRqoLhhZI4HhWtncYziFLN4dMNjChpLoh2nHDI7kXaJtYx2y7jaiUQ5Vu4Uo4cD3geigp9Ij7EiogqfKw+dcga5/zf2hDQawgnaVQa6o3XNmGyubSlplfIZjoM1cWW+jMjyHVLpPOTv7nzpAtgOxTu4SkzeZZSYCyiGslnrK91CkkaD1rkIXM9WSpvOFL0saiI+Hzw9hNZaPZYFkDpyaDpEV0xR9tSETkIY0ZcwXdK4CxY3qFGDXl9IX6a+OYxkix3mroi31vWj6xcr7v2r17V2hWP4WQ9aaBLYANfPwe2eLnR6uOqiWWOj0nMHkLzBe1nh+JZoqGGRZuhnQxqLf7IJEU1S/odTId+3/TEk9V4Wh4vkXo6O4U+A0xWKv6xmjV05fjQKWVnf3fuowT/qSO1rNNmT/dRulT3rKS0qYaQ5TftVkhXB7ngQoeav/jYY8Q7+f4YWY+uTymu//4cJ5dSiHBpZ719NhllaHlzhvFTaz6Fpzmo4TNmYAd7gHaIaISLg3767qMbAOUCSkY/xDt1a1w74c9olDytdNd0Lo=
